/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

WITH CTE
AS (
	SELECT 1 AS n
		,0 AS low
		,1 AS high
	
	UNION ALL
	
	SELECT n + 1
		,high
		,high + low
	FROM CTE
	WHERE low + high < 4000000
	)
SELECT SUM(high)
FROM CTE
WHERE high % 2 = 0
